package com.marinj.shoppingwarfare.ui

import androidx.compose.ui.graphics.Color

val purpleDark = Color(0xFF7c4dff)
val purpleLight = Color(0xFF651fff)
val purple = Color(0xFF3f1dcb)
val white = Color(0xFFFFFFFF)

val md_theme_light_primary = Color(0xFF8441A2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF7D8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF320047)
val md_theme_light_secondary = Color(0xFF6750A4)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE9DDFF)
val md_theme_light_onSecondaryContainer = Color(0xFF22005D)
val md_theme_light_tertiary = Color(0xFF815250)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD8)
val md_theme_light_onTertiaryContainer = Color(0xFF331111)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B1E)
val md_theme_light_surfaceVariant = Color(0xFFEBDFEA)
val md_theme_light_onSurfaceVariant = Color(0xFF4C444D)
val md_theme_light_outline = Color(0xFF7D747D)
val md_theme_light_inverseOnSurface = Color(0xFFF6EFF3)
val md_theme_light_inverseSurface = Color(0xFF332F33)
val md_theme_light_inversePrimary = Color(0xFFEAB2FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8441A2)
val md_theme_light_outlineVariant = Color(0xFFCEC3CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFEAB2FF)
val md_theme_dark_onPrimary = Color(0xFF50056F)
val md_theme_dark_primaryContainer = Color(0xFF6A2788)
val md_theme_dark_onPrimaryContainer = Color(0xFFF7D8FF)
val md_theme_dark_secondary = Color(0xFFCFBDFF)
val md_theme_dark_onSecondary = Color(0xFF371E73)
val md_theme_dark_secondaryContainer = Color(0xFF4E378A)
val md_theme_dark_onSecondaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_tertiary = Color(0xFFF5B7B5)
val md_theme_dark_onTertiary = Color(0xFF4C2524)
val md_theme_dark_tertiaryContainer = Color(0xFF663B3A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B1E)
val md_theme_dark_onBackground = Color(0xFFE8E0E5)
val md_theme_dark_surface = Color(0xFF1E1B1E)
val md_theme_dark_onSurface = Color(0xFFE8E0E5)
val md_theme_dark_surfaceVariant = Color(0xFF4C444D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC3CD)
val md_theme_dark_outline = Color(0xFF978E97)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE8E0E5)
val md_theme_dark_inversePrimary = Color(0xFF8441A2)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFEAB2FF)
val md_theme_dark_outlineVariant = Color(0xFF4C444D)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF8441A2)
