name: Android CI

on: [push, pull_request]

jobs:
  static_analysis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: ktlint
        run: ./gradlew ktlintCheck
      - name: detekt
        run: ./gradlew detekt
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build android app
        run: ./gradlew assembleDebug --stacktrace
      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest --stacktrace
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run Unit Tests
        run: ./gradlew testReleaseUnitTest --stacktrace
